### ISSUE TITLE
Remove assignments after role updates

### ISSUE THREAD

**Issue by Gerych1984** [yiisoft/rbac-php#25]
Good day. After use method `$manager::updateRole` all assignments was removed. Thanks

**Comment by samdark** [comment]
@Gerych1984 do you want assignments to be removed after `updateRole`?

**Comment by Gerych1984** [comment]
> @Gerych1984 do you want assignments to be removed after `updateRole`?

No, I think it's are bug. My profile has role "admin" with some error description. After I fix description and save using `updateRole` method my profile became without role, and assignment file contains be empty array

**Comment by darkdef** [comment]
> > @Gerych1984 do you want assignments to be removed after `updateRole`?
> 
> No, I think it's are bug. My profile has role "admin" with some error description. After I fix description and save using `updateRole` method my profile became without role, and assignment file contains empty array

Please add example of usage

**Comment by Gerych1984** [comment]
> > > @Gerych1984 do you want assignments to be removed after `updateRole`?
> > 
> > 
> > No, I think it's are bug. My profile has role "admin" with some error description. After I fix description and save using `updateRole` method my profile became without role, and assignment file contains empty array
> 
> Please add example of usage

My case
```
$role = (new Role('test-role'))->withDescription('err description');
$manager->addRole($role);
$manager->assign($role, 'test-user');

var_dump($this->manager->getRolesByUser('test-user')); //array with two roles - "Demo" default for all users and "test-role"

$role = $role->withDescription('Right description');
$manager->updateRole('test-role', $role);

var_dump($this->manager->getRolesByUser('test-user')); //array with one default "Demo" role
```

**Comment by darkdef** [comment]
Yes, i understand. You change only description of role
https://github.com/yiisoft/rbac-php/blob/f3dcd7e2a52d0494bc35f2ff371db2ddaa85a1aa/src/AssignmentsStorage.php#L85

It's bug. Will be fixed
